/* UI copy of the redesign in the six site languages. Data (experiences, projects, CV titles)
   still comes from translations.js; this file holds the editorial copy of the sections. */
const RD = {
  english: {
    nav: { work: "Work", path: "Path", about: "About" },
    labels: ["Data & AI", "Product", "Business", "Delivery"],
    loc: "Based in Zürich · Working internationally", cta: "Explore my work", scroll: "Scroll ↓",
    intro: ["I turn ", "ambiguous problems", " into data, decisions and things that ship."],
    summary: "Data scientist and product owner who joins teams to turn new technology into working solutions. 4+ years shipping decision-driving models, dashboards and AI tools across banking, marketing, industrial and public-sector problems — from the first conversation with the business to code in production. Comfortable in ambiguity, fast at learning a new domain, and at ease bridging engineers, analysts and senior stakeholders in six languages.",
    s1: { title: ["I make sense", "of complexity"], lead: "From a vague business question to a working prototype — statistics, ML and LLMs, always in service of a decision someone has to make.", listTitle: "Expertise",
      list: ["Rapid prototyping", "LLM integration (Claude API, embeddings)", "Forecasting & anomaly detection", "Experiment design", "Dashboard & KPI design", "Production delivery (CI, Docker)"] },
    s2: { title: ["I connect", "the dots"], lead: "I'm the person between the engineers and the business — the one who makes both sides understood.", listTitle: "/ Cross-functional impact",
      list: ["Led a cross-functional pod of 5 — project time −50%", "Product owner of 2 risk tools in production at UBS", "Embedded with Google product & engineering teams", "Mentored an intern for 1.5 years", "Work in 6 languages across ES · CH · global teams"] },
    s3: { title: ["I make", "things happen"], lead: "Selected projects, from zero to shipped. Click any card for the full story." },
    s4: { title: ["My path isn't", "a straight line"], lead: "Different roles, sectors and countries — one trajectory. Growth is layers of learning and impact.", legend: { work: "WORK", studies: "STUDIES" } },
    s5: "Full experience", footer: "Let's talk", modal: { open: "Open live ↗", code: "View code ↗" },
    methods: ["Rapid prototyping", "LLM integration (Claude API, embeddings)", "Forecasting & anomaly detection", "Experiment design", "Dashboard & KPI design", "Production delivery (CI, Docker)", "Stakeholder management", "Agile (Scrum)"],
  },
  catalan: {
    nav: { work: "Projectes", path: "Trajectòria", about: "Sobre mi" },
    labels: ["Dades i IA", "Producte", "Negoci", "Lliurament"],
    loc: "A Zürich · Treballant internacionalment", cta: "Explora la meva feina", scroll: "Baixa ↓",
    intro: ["Converteixo ", "problemes ambigus", " en dades, decisions i coses que surten a producció."],
    summary: "Data scientist i product owner que s'incorpora a equips per convertir tecnologia nova en solucions que funcionen. Més de 4 anys posant en producció models que orienten decisions, dashboards i eines d'IA en banca, màrqueting, indústria i sector públic — des de la primera conversa amb negoci fins al codi en producció. Còmoda en l'ambigüitat, ràpida aprenent un domini nou i acostumada a fer de pont entre enginyers, analistes i directius en sis idiomes.",
    s1: { title: ["Dono sentit", "a la complexitat"], lead: "D'una pregunta de negoci difusa a un prototip que funciona — estadística, ML i LLMs, sempre al servei d'una decisió que algú ha de prendre.", listTitle: "Expertesa",
      list: ["Prototipatge ràpid", "Integració de LLMs (API de Claude, embeddings)", "Previsió i detecció d'anomalies", "Disseny d'experiments", "Disseny de dashboards i KPIs", "Lliurament a producció (CI, Docker)"] },
    s2: { title: ["Connecto", "els punts"], lead: "Soc la persona entre els enginyers i el negoci — la que fa que les dues bandes s'entenguin.", listTitle: "/ Impacte transversal",
      list: ["Vaig liderar un pod transversal de 5 — temps de projecte −50 %", "Product owner de 2 eines de risc en producció a UBS", "Integrada amb equips de producte i enginyeria de Google", "Vaig mentoritzar una becària durant 1,5 anys", "Treballo en 6 idiomes, entre ES · CH · equips globals"] },
    s3: { title: ["Faig que", "les coses passin"], lead: "Projectes seleccionats, de zero a producció. Clica qualsevol card per veure la història sencera." },
    s4: { title: ["El meu camí no és", "una línia recta"], lead: "Rols, sectors i països diferents — una sola trajectòria. Créixer és acumular capes d'aprenentatge i impacte.", legend: { work: "FEINA", studies: "ESTUDIS" } },
    s5: "Experiència completa", footer: "Parlem", modal: { open: "Obre la demo ↗", code: "Veure el codi ↗" },
    methods: ["Prototipatge ràpid", "Integració de LLMs (API de Claude, embeddings)", "Previsió i detecció d'anomalies", "Disseny d'experiments", "Disseny de dashboards i KPIs", "Lliurament a producció (CI, Docker)", "Gestió d'stakeholders", "Agile (Scrum)"],
  },
  spanish: {
    nav: { work: "Proyectos", path: "Trayectoria", about: "Sobre mí" },
    labels: ["Datos e IA", "Producto", "Negocio", "Entrega"],
    loc: "En Zúrich · Trabajando internacionalmente", cta: "Explora mi trabajo", scroll: "Baja ↓",
    intro: ["Convierto ", "problemas ambiguos", " en datos, decisiones y cosas que llegan a producción."],
    summary: "Data scientist y product owner que se incorpora a equipos para convertir tecnología nueva en soluciones que funcionan. Más de 4 años poniendo en producción modelos que orientan decisiones, dashboards y herramientas de IA en banca, marketing, industria y sector público — desde la primera conversación con negocio hasta el código en producción. Cómoda en la ambigüedad, rápida aprendiendo un dominio nuevo y acostumbrada a hacer de puente entre ingenieros, analistas y directivos en seis idiomas.",
    s1: { title: ["Doy sentido", "a la complejidad"], lead: "De una pregunta de negocio difusa a un prototipo que funciona — estadística, ML y LLMs, siempre al servicio de una decisión que alguien tiene que tomar.", listTitle: "Experiencia",
      list: ["Prototipado rápido", "Integración de LLMs (API de Claude, embeddings)", "Previsión y detección de anomalías", "Diseño de experimentos", "Diseño de dashboards y KPIs", "Entrega a producción (CI, Docker)"] },
    s2: { title: ["Conecto", "los puntos"], lead: "Soy la persona entre los ingenieros y el negocio — la que hace que ambas partes se entiendan.", listTitle: "/ Impacto transversal",
      list: ["Lideré un pod transversal de 5 — tiempo de proyecto −50 %", "Product owner de 2 herramientas de riesgo en producción en UBS", "Integrada con equipos de producto e ingeniería de Google", "Mentoricé a una becaria durante 1,5 años", "Trabajo en 6 idiomas, entre ES · CH · equipos globales"] },
    s3: { title: ["Hago que", "las cosas pasen"], lead: "Proyectos seleccionados, de cero a producción. Haz clic en cualquier card para ver la historia completa." },
    s4: { title: ["Mi camino no es", "una línea recta"], lead: "Roles, sectores y países distintos — una sola trayectoria. Crecer es acumular capas de aprendizaje e impacto.", legend: { work: "TRABAJO", studies: "ESTUDIOS" } },
    s5: "Experiencia completa", footer: "Hablemos", modal: { open: "Abrir demo ↗", code: "Ver código ↗" },
    methods: ["Prototipado rápido", "Integración de LLMs (API de Claude, embeddings)", "Previsión y detección de anomalías", "Diseño de experimentos", "Diseño de dashboards y KPIs", "Entrega a producción (CI, Docker)", "Gestión de stakeholders", "Agile (Scrum)"],
  },
  french: {
    nav: { work: "Projets", path: "Parcours", about: "À propos" },
    labels: ["Données & IA", "Produit", "Business", "Livraison"],
    loc: "Basée à Zurich · Travaille à l'international", cta: "Découvrir mon travail", scroll: "Défiler ↓",
    intro: ["Je transforme des ", "problèmes ambigus", " en données, en décisions et en produits livrés."],
    summary: "Data scientist et product owner qui rejoint les équipes pour transformer une technologie nouvelle en solutions qui fonctionnent. Plus de 4 ans à mettre en production des modèles d'aide à la décision, des dashboards et des outils d'IA — banque, marketing, industrie et secteur public — de la première conversation avec le métier jusqu'au code en production. À l'aise dans l'ambiguïté, rapide à apprendre un nouveau domaine, et habituée à faire le lien entre ingénieurs, analystes et dirigeants, en six langues.",
    s1: { title: ["Je donne du sens", "à la complexité"], lead: "D'une question métier floue à un prototype qui fonctionne — statistiques, ML et LLM, toujours au service d'une décision que quelqu'un doit prendre.", listTitle: "Expertise",
      list: ["Prototypage rapide", "Intégration de LLM (API Claude, embeddings)", "Prévision et détection d'anomalies", "Design d'expériences", "Design de dashboards et de KPI", "Mise en production (CI, Docker)"] },
    s2: { title: ["Je relie", "les points"], lead: "Je suis la personne entre les ingénieurs et le métier — celle qui fait que les deux côtés se comprennent.", listTitle: "/ Impact transversal",
      list: ["Pilotage d'un pod transversal de 5 — temps de projet −50 %", "Product owner de 2 outils de risque en production chez UBS", "Intégrée aux équipes produit et ingénierie de Google", "Mentorat d'une stagiaire pendant 1,5 an", "Je travaille en 6 langues, entre ES · CH · équipes globales"] },
    s3: { title: ["Je fais", "avancer les choses"], lead: "Projets sélectionnés, de zéro à la mise en production. Cliquez sur une carte pour l'histoire complète." },
    s4: { title: ["Mon parcours n'est pas", "une ligne droite"], lead: "Des rôles, des secteurs et des pays différents — une seule trajectoire. Grandir, c'est empiler des couches d'apprentissage et d'impact.", legend: { work: "TRAVAIL", studies: "ÉTUDES" } },
    s5: "Expérience complète", footer: "Parlons-en", modal: { open: "Ouvrir la démo ↗", code: "Voir le code ↗" },
    methods: ["Prototypage rapide", "Intégration de LLM (API Claude, embeddings)", "Prévision et détection d'anomalies", "Design d'expériences", "Design de dashboards et de KPI", "Mise en production (CI, Docker)", "Gestion des parties prenantes", "Agile (Scrum)"],
  },
  german: {
    nav: { work: "Projekte", path: "Werdegang", about: "Über mich" },
    labels: ["Daten & KI", "Produkt", "Business", "Delivery"],
    loc: "In Zürich · International tätig", cta: "Meine Arbeit entdecken", scroll: "Scrollen ↓",
    intro: ["Ich verwandle ", "unklare Probleme", " in Daten, Entscheidungen und Dinge, die live gehen."],
    summary: "Data Scientist und Product Owner, die zu Teams stösst, um neue Technologie in funktionierende Lösungen zu verwandeln. Über 4 Jahre entscheidungsrelevante Modelle, Dashboards und KI-Tools in Produktion gebracht — Banking, Marketing, Industrie und öffentlicher Sektor — vom ersten Gespräch mit dem Business bis zum Code in Produktion. Wohl in der Ambiguität, schnell in neuen Domänen und geübt darin, zwischen Engineers, Analysten und Führungskräften zu vermitteln — in sechs Sprachen.",
    s1: { title: ["Ich bringe Sinn", "in Komplexität"], lead: "Von einer vagen Business-Frage zum funktionierenden Prototyp — Statistik, ML und LLMs, immer im Dienst einer Entscheidung, die jemand treffen muss.", listTitle: "Expertise",
      list: ["Rapid Prototyping", "LLM-Integration (Claude API, Embeddings)", "Forecasting & Anomalieerkennung", "Experimentdesign", "Dashboard- & KPI-Design", "Production Delivery (CI, Docker)"] },
    s2: { title: ["Ich verbinde", "die Punkte"], lead: "Ich bin die Person zwischen den Engineers und dem Business — die dafür sorgt, dass beide Seiten sich verstehen.", listTitle: "/ Bereichsübergreifende Wirkung",
      list: ["Leitung eines cross-funktionalen Pods von 5 — Projektzeit −50 %", "Product Owner von 2 Risiko-Tools in Produktion bei UBS", "Eingebettet in Produkt- und Engineering-Teams bei Google", "1,5 Jahre Mentoring einer Praktikantin", "Arbeit in 6 Sprachen, zwischen ES · CH · globalen Teams"] },
    s3: { title: ["Ich bringe", "Dinge ins Rollen"], lead: "Ausgewählte Projekte, von null bis live. Klicke auf eine Karte für die ganze Geschichte." },
    s4: { title: ["Mein Weg ist", "keine gerade Linie"], lead: "Verschiedene Rollen, Branchen und Länder — eine Laufbahn. Wachstum sind Schichten aus Lernen und Wirkung.", legend: { work: "ARBEIT", studies: "STUDIUM" } },
    s5: "Gesamte Erfahrung", footer: "Reden wir", modal: { open: "Demo öffnen ↗", code: "Code ansehen ↗" },
    methods: ["Rapid Prototyping", "LLM-Integration (Claude API, Embeddings)", "Forecasting & Anomalieerkennung", "Experimentdesign", "Dashboard- & KPI-Design", "Production Delivery (CI, Docker)", "Stakeholder-Management", "Agile (Scrum)"],
  },
  italian: {
    nav: { work: "Progetti", path: "Percorso", about: "Chi sono" },
    labels: ["Dati & AI", "Prodotto", "Business", "Delivery"],
    loc: "A Zurigo · Lavoro a livello internazionale", cta: "Scopri il mio lavoro", scroll: "Scorri ↓",
    intro: ["Trasformo ", "problemi ambigui", " in dati, decisioni e cose che vanno in produzione."],
    summary: "Data scientist e product owner che si unisce ai team per trasformare nuove tecnologie in soluzioni che funzionano. Oltre 4 anni a portare in produzione modelli a supporto delle decisioni, dashboard e strumenti di AI — banca, marketing, industria e settore pubblico — dalla prima conversazione con il business fino al codice in produzione. A mio agio nell'ambiguità, veloce a imparare un nuovo dominio e abituata a fare da ponte tra ingegneri, analisti e dirigenti, in sei lingue.",
    s1: { title: ["Do un senso", "alla complessità"], lead: "Da una domanda di business vaga a un prototipo funzionante — statistica, ML e LLM, sempre al servizio di una decisione che qualcuno deve prendere.", listTitle: "Competenze",
      list: ["Prototipazione rapida", "Integrazione di LLM (API Claude, embeddings)", "Previsione e rilevamento di anomalie", "Design di esperimenti", "Design di dashboard e KPI", "Rilascio in produzione (CI, Docker)"] },
    s2: { title: ["Collego", "i punti"], lead: "Sono la persona tra gli ingegneri e il business — quella che fa sì che le due parti si capiscano.", listTitle: "/ Impatto trasversale",
      list: ["Ho guidato un pod trasversale di 5 — tempo di progetto −50 %", "Product owner di 2 strumenti di rischio in produzione in UBS", "Integrata nei team di prodotto e ingegneria di Google", "Ho fatto da mentore a una stagista per 1,5 anni", "Lavoro in 6 lingue, tra ES · CH · team globali"] },
    s3: { title: ["Faccio", "accadere le cose"], lead: "Progetti selezionati, da zero alla produzione. Clicca su una card per la storia completa." },
    s4: { title: ["Il mio percorso non è", "una linea retta"], lead: "Ruoli, settori e paesi diversi — una sola traiettoria. Crescere è accumulare strati di apprendimento e impatto.", legend: { work: "LAVORO", studies: "STUDI" } },
    s5: "Esperienza completa", footer: "Parliamone", modal: { open: "Apri la demo ↗", code: "Vedi il codice ↗" },
    methods: ["Prototipazione rapida", "Integrazione di LLM (API Claude, embeddings)", "Previsione e rilevamento di anomalie", "Design di esperimenti", "Design di dashboard e KPI", "Rilascio in produzione (CI, Docker)", "Gestione degli stakeholder", "Agile (Scrum)"],
  },
};
export default RD;
